# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.8.4.dev6+dirty'
__version_tuple__ = version_tuple = (0, 8, 4, 'dev6', 'dirty')
